version: "3.8"

services:
  awscollector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: awscollector
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    ports:
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55680:55680"
      - "8889:8888"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-northeast-1
